spring.application.name=LAL.MobileGuns
server.servlet.context-path=/LAL.MobileGuns

#Port
server.port= 18115
#Informations de connexion a la DB
spring.datasource.url=jdbc:oracle:thin:@//svlalgbugedd:1521/gesdbd
spring.datasource.username=UGFAB
spring.datasource.password=ugfab
# JWT
app.secret-key=LALMobileGunsSecretKeyNLMKBelgium2024VeryLongSecretKey
app.expiration-time=86400000
user_guide_complete_path=C:/temp/user-guide.pdf